# Generated by Django 4.0.4 on 2022-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity', models.PositiveIntegerField(default=2, verbose_name='Необходимая производительность')),
                ('water_temperature', models.PositiveIntegerField(default=70, verbose_name='Температура деаэрации')),
            ],
        ),
    ]
