# Generated by Django 4.0.4 on 2022-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialdata',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата заполнения'),
        ),
    ]
