# Generated by Django 4.0.4 on 2022-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0002_initialdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialdata',
            name='productivity',
        ),
        migrations.AddField(
            model_name='initialdata',
            name='productivity_max',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=5, verbose_name='Необходимая номинальная производительность'),
        ),
        migrations.AddField(
            model_name='initialdata',
            name='productivity_min',
            field=models.DecimalField(decimal_places=1, default=0.6, max_digits=5, verbose_name='Необходимая производительность'),
        ),
    ]
