# Generated by Django 4.0.4 on 2022-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0003_remove_initialdata_productivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialdata',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечания'),
        ),
    ]
