# Generated by Django 4.0.4 on 2022-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0008_initialdata_condensate_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialdata',
            name='condensate_flow',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Расход конденсата на деаэратор, т/ч'),
        ),
    ]
