# Generated by Django 4.0.4 on 2022-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0009_alter_initialdata_condensate_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialdata',
            name='is_steam_saturated',
            field=models.BooleanField(default=True, verbose_name='Насыщенный пар'),
        ),
    ]
