# Generated by Django 4.0.4 on 2022-04-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0010_initialdata_is_steam_saturated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialdata',
            name='is_steam_saturated',
        ),
    ]
