# Generated by Django 4.0.4 on 2022-04-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0012_heatbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeatBalance',
        ),
    ]
