# Generated by Django 4.0.4 on 2022-04-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0013_delete_heatbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_data.initialdata', verbose_name='Номер заказа')),
            ],
        ),
    ]
