# Generated by Django 4.0.4 on 2022-04-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_data', '0014_heatbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialdata',
            options={'ordering': ('date', 'id'), 'verbose_name': 'Исходные данные к проекту', 'verbose_name_plural': 'Исходные данные к проекту'},
        ),
        migrations.DeleteModel(
            name='HeatBalance',
        ),
    ]
