# Generated by Django 4.0.4 on 2022-04-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initial_data', '0003_remove_initialdata_productivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_initdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_data.initialdata', verbose_name='Выберите запрос')),
            ],
        ),
    ]
